# Generated by Django 3.0.6 on 2020-06-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='收件人', max_length=10)),
                ('tel', models.CharField(help_text='电话', max_length=20)),
                ('address', models.CharField(help_text='收货地址', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='user.User')),
            ],
            options={
                'db_table': 'adressInfo',
            },
        ),
    ]
