# Generated by Django 3.0.6 on 2020-06-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_addressinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
