# Generated by Django 3.0.6 on 2020-07-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_reg_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinfo',
            name='postcode',
            field=models.CharField(blank=True, help_text='邮编', max_length=20, null=True),
        ),
    ]
