# Generated by Django 3.0.6 on 2020-07-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_addressinfo_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='user.User'),
        ),
    ]
