# Generated by Django 3.0.6 on 2020-06-30 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=20, verbose_name='名字')),
                ('commodity_price', models.CharField(max_length=20)),
                ('commodity_unit', models.CharField(max_length=50)),
                ('intorduction', models.CharField(help_text='简介', max_length=100)),
                ('description', models.CharField(help_text='详情描述', max_length=200)),
                ('commodity_type', models.CharField(blank=True, help_text='商品类型', max_length=20, null=True)),
                ('img_name', models.CharField(blank=True, help_text='照片名', max_length=20, null=True)),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('num', models.IntegerField(verbose_name='数量')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='commodity.Commodity')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
